"""Generate the simulated ArUco marker assets and the perception setup from one declaration.

The declaration file (``markers.yml``) is the source of truth: the marker PNGs, the marker MJCF
assets and the setup YAML are outputs of this generator and must never be hand-edited.
"""

import argparse
import os
import xml.etree.ElementTree as ET
from pathlib import Path

import cv2
import numpy as np
import yaml
from scipy.spatial.transform import Rotation as R

DEFAULT_DICTIONARY = 'DICT_4X4_50'
GENERATED_BY = 'generated by aruco_perception.sim_markers from markers.yml; do not hand-edit'

MJCF_TEMPLATE = """<!-- {note} -->
<mujoco model="aruco_marker_{marker_id}">
  <asset>
    <texture name="aruco_{marker_id}_tex" type="2d" file="marker_{marker_id}.png"/>
    <material name="aruco_{marker_id}_mat" texture="aruco_{marker_id}_tex" texrepeat="1 1"
              texuniform="false" specular="0" shininess="0" reflectance="0" emission="0.35"/>
  </asset>
  <worldbody>
    <body name="root">
      <geom name="marker" type="box" size="{half:.7f} {half:.7f} 0.0005" pos="0 0 0.0005"
            material="aruco_{marker_id}_mat" mass="0.01" contype="0" conaffinity="0"/>
    </body>
  </worldbody>
</mujoco>
"""


def predefined_dictionary(dictionary_name):
    """Resolve one predefined ArUco dictionary by its cv2.aruco constant name."""
    constant = getattr(cv2.aruco, dictionary_name, None)
    if constant is None:
        raise ValueError(f'Invalid marker dictionary: {dictionary_name}')
    return cv2.aruco.getPredefinedDictionary(constant)


def module_count(dictionary_name):
    """Modules across the printed black square: data modules plus a one-module border."""
    return int(predefined_dictionary(dictionary_name).markerSize) + 2


def marker_image(dictionary_name, marker_id, module_px, quiet_modules):
    """The marker as a numpy uint8 image, padded with a white quiet zone."""
    if module_px < 1 or quiet_modules < 0:
        raise ValueError('module_px must be positive and quiet_modules non-negative')
    modules = module_count(dictionary_name)
    square = cv2.aruco.generateImageMarker(
        predefined_dictionary(dictionary_name), int(marker_id), modules * module_px
    )
    pad = quiet_modules * module_px
    return cv2.copyMakeBorder(
        square, pad, pad, pad, pad, cv2.BORDER_CONSTANT, value=255
    ).astype(np.uint8)


def geom_half_extent(size_m, quiet_modules, dictionary_name):
    """Half the physical side of the padded sheet; marker_size covers only the black square."""
    modules = module_count(dictionary_name)
    return size_m * (modules + 2 * quiet_modules) / modules / 2.0


def marker_mjcf(marker_id, size_m, quiet_modules, dictionary_name):
    """The MJCF text for one marker: texture, unlit material, and a 1 mm box."""
    return MJCF_TEMPLATE.format(
        note=GENERATED_BY,
        marker_id=int(marker_id),
        half=geom_half_extent(size_m, quiet_modules, dictionary_name),
    )


def mount_rotation(euler_zyx_deg):
    """The mount's rotation, authored the way the scenex authors one: intrinsic z-y-x degrees."""
    return R.from_euler('ZYX', [float(a) for a in euler_zyx_deg], degrees=True)


def _child(parent, tag):
    """The named child, appended if the host asset does not already carry one."""
    found = parent.find(tag)
    if found is None:
        found = ET.SubElement(parent, tag)
    return found


def _body(root, name):
    """One named body anywhere under the host's worldbody."""
    for body in root.iter('body'):
        if body.get('name') == name:
            return body
    raise ValueError(f"host asset has no body named '{name}'")


def mount_markers(spec, asset_dir):
    """Print mounted markers onto a copy of their host asset, so they ride the body they are on.

    A marker welded onto a modelled object's frame loses its offset in lowering, so a marker that
    must move with an object belongs in that object's MJCF rather than beside it.
    """
    dictionary = spec.get('dictionary', DEFAULT_DICTIONARY)
    quiet_modules = int(spec.get('quiet_modules', 1))

    hosts = {}
    for marker in spec['markers']:
        mount = marker.get('mount')
        if mount is None:
            continue
        hosts.setdefault((mount['asset'], mount['out']), []).append((marker, mount))

    written = []
    for (asset_rel, out_rel), mounted in hosts.items():
        source = (asset_dir / asset_rel).resolve()
        target = (asset_dir / out_rel).resolve()
        parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
        tree = ET.parse(source, parser=parser)
        root = tree.getroot()
        assets = _child(root, 'asset')

        for marker, mount in mounted:
            marker_id = int(marker['id'])
            half = geom_half_extent(float(marker['size']), quiet_modules, dictionary)
            texture = os.path.relpath(asset_dir / f'marker_{marker_id}.png', target.parent)
            ET.SubElement(assets, 'texture', {
                'name': f'aruco_{marker_id}_tex', 'type': '2d', 'file': texture,
            })
            ET.SubElement(assets, 'material', {
                'name': f'aruco_{marker_id}_mat', 'texture': f'aruco_{marker_id}_tex',
                'texrepeat': '1 1', 'texuniform': 'false', 'specular': '0', 'shininess': '0',
                'reflectance': '0', 'emission': '0.35',
            })

            rotation = mount_rotation(mount.get('euler', (0.0, 0.0, 0.0)))
            # The declared pose is the printed face's frame; the sheet's centre sits half its
            # thickness behind it, along the marker's own outward normal.
            origin = np.asarray([float(v) for v in mount['pos']], dtype=float)
            centre = origin + rotation.apply([0.0, 0.0, 0.0005])
            quat = rotation.as_quat()
            ET.SubElement(_body(root, mount['body']), 'geom', {
                'name': f'aruco_{marker_id}',
                'type': 'box',
                'size': f'{half:.7f} {half:.7f} 0.0005',
                'pos': ' '.join(f'{v:.7f}' for v in centre),
                'quat': ' '.join(f'{v:.9f}' for v in (quat[3], quat[0], quat[1], quat[2])),
                'material': f'aruco_{marker_id}_mat',
                'mass': '0.001',
                'contype': '0',
                'conaffinity': '0',
            })

        ET.indent(tree, space='  ')
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open('wb') as handle:
            handle.write(f'<!-- {GENERATED_BY} -->\n'.encode())
            tree.write(handle, encoding='utf-8', xml_declaration=False)
        written.append(target)
    return written


def setup_config(spec, sensors, model, ref_frame, frames, objects):
    """The aruco_perception setup mapping, built from the marker declarations."""
    marker_frames = []
    for marker in spec['markers']:
        frame = {'frame': marker['frame']}
        if 'iri' in marker:
            frame['iri'] = marker['iri']
        frame['marker'] = {
            'marker_size': float(marker['size']),
            'marker_id': int(marker['id']),
        }
        marker_frames.append(frame)

    return {
        'marker_dict': spec.get('dictionary', DEFAULT_DICTIONARY),
        'sensors': sensors,
        'model': model,
        'frames': marker_frames + list(frames),
        'ref_frame': ref_frame,
        'objects': objects,
    }


def write_marker_assets(spec, asset_dir):
    """Write one PNG and one MJCF per declared marker; the texture is resolved beside the XML."""
    dictionary = spec.get('dictionary', DEFAULT_DICTIONARY)
    module_px = int(spec.get('module_px', 100))
    quiet_modules = int(spec.get('quiet_modules', 1))
    asset_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for marker in spec['markers']:
        marker_id = int(marker['id'])
        image_path = asset_dir / f'marker_{marker_id}.png'
        if not cv2.imwrite(
            str(image_path), marker_image(dictionary, marker_id, module_px, quiet_modules)
        ):
            raise OSError(f'could not write {image_path}')
        written.append(image_path)
        if marker.get('mount') is not None:
            continue
        mjcf_path = asset_dir / f'marker_{marker_id}.xml'
        mjcf_path.write_text(
            marker_mjcf(marker_id, float(marker['size']), quiet_modules, dictionary)
        )
        written.append(mjcf_path)
    return written


def main(argv=None):
    """CLI: read markers.yml, write the PNGs, the MJCFs and the setup YAML."""
    parser = argparse.ArgumentParser(
        description='Generate ArUco marker assets and the perception setup from markers.yml'
    )
    parser.add_argument('--markers', required=True, type=Path, help='marker declaration file')
    parser.add_argument('--asset-dir', required=True, type=Path, help='where the PNG/XML go')
    parser.add_argument('--setup-out', required=True, type=Path, help='setup YAML to write')
    args = parser.parse_args(argv)

    spec = yaml.safe_load(args.markers.read_text())
    if not isinstance(spec, dict) or not spec.get('markers'):
        raise ValueError(f"'{args.markers}' must be a mapping declaring at least one marker")

    for path in write_marker_assets(spec, args.asset_dir):
        print(path)
    for path in mount_markers(spec, args.asset_dir):
        print(path)

    config = setup_config(
        spec,
        spec['sensors'],
        spec['model'],
        spec['ref_frame'],
        spec.get('frames', []),
        spec.get('objects', []),
    )
    args.setup_out.parent.mkdir(parents=True, exist_ok=True)
    args.setup_out.write_text(
        f'# {GENERATED_BY}\n' + yaml.safe_dump(config, sort_keys=False, default_flow_style=False)
    )
    print(args.setup_out)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
