static_camera:
  image_topic: /camera/camera/color/image_raw
  camera_info_topic: /camera/camera/color/camera_info

arm_camera:
  ip: 192.168.1.10
  image_topic: /camera/color/image_raw
  camera_info_topic: /camera/color/camera_info

scene:
  file_path: src/scene-dsl/examples/generated/lab.scenex.json

world_marker:
  frame: table_anchor
  iri: https://secorolab.github.io/models/scenes/admittance-arc-single-mjc/world_tree/robot-table-body/table_anchor
  marker_dict: DICT_4X4_50
  marker_size: 0.1
  marker_id: 0

objects:
  marker_dict: DICT_4X4_50
  marker_size: 0.05

tray:
  handle_frame: aruco_1
  marker_front:
    id: 1
    offset:
      x: -0.065
      y: 0.0
      z: 0.02
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  marker_back:
    id: 2
    offset:
      x: 0.0
      y: 0.0
      z: -0.22
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
